#!/usr/bin/env python


import open3d as o3d
import numpy as np
from sys import argv

if __name__ == "__main__":
    if len(argv) != 1:
        print("You should enter 1 parameter: <nbees>")


    #Read pcd file
    pcd = o3d.io.read_point_cloud(argv[1])
    pcd2 = o3d.io.read_point_cloud(argv[2])

    # Visualize it
    o3d.visualization.draw_geometries([pcd,pcd2])
